### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by SkJsonTeam** [faketunaPrivateCamp/SkriptWebAPI#6]
Hello there, i wanna help you with skwebapi, cause i working on templating system for skript.

```html
<html lang="cs">
    <head>
        <title>New Page</title>
    </head>
    <body>
        <h1>New Page</h1>
        <h2>Special test</h2>
        _{if ("A" != "A")}_:
            <h2>Tento text by měl být zobrazen</h2>
        _{else}_:
            <h2>Tento text by neměl být zobrazen</h2>
        _{/if}_
    </body>
</html>
```

**Comment by faketuna** [comment]
Hello SKJsonTeam Sorry for late reply.


short summary: 
I'm interested that suggestion, but I may not make it all the way through because I have very little current interest in Minecraft and java.

long: 
Im so much interested the suggestion.
But I have very little current interest in Minecraft and java.

SkriptWebAPI code is so bad I think, so I want refactor the code before implement something.

Also, I am now a developer for csgo community server. I may not be able to get much time for this suggestion as I am spending a lot of time developing plugins for the csgo server.

If you don't mind the above, please send a DM to Discord: ftnd (since I don't check GitHub often)

**Comment by SkJsonTeam** [comment]
Hello again,
The Discord request was sended from `.coffeerequired`
I wish you nice evening.

**Comment by faketuna** [comment]
Accepted! We will disscuss in discord, so I will close this issue.
